// Dataset lengkap untuk latihan bahasa Jepang

// HIRAGANA (46 karakter dasar)
const hiraganaData = [
    // Baris A
    { char: 'あ', romaji: 'a', kategori: 'a-gyou' },
    { char: 'い', romaji: 'i', kategori: 'a-gyou' },
    { char: 'う', romaji: 'u', kategori: 'a-gyou' },
    { char: 'え', romaji: 'e', kategori: 'a-gyou' },
    { char: 'お', romaji: 'o', kategori: 'a-gyou' },
    // Baris KA
    { char: 'か', romaji: 'ka', kategori: 'ka-gyou' },
    { char: 'き', romaji: 'ki', kategori: 'ka-gyou' },
    { char: 'く', romaji: 'ku', kategori: 'ka-gyou' },
    { char: 'け', romaji: 'ke', kategori: 'ka-gyou' },
    { char: 'こ', romaji: 'ko', kategori: 'ka-gyou' },
    // Baris SA
    { char: 'さ', romaji: 'sa', kategori: 'sa-gyou' },
    { char: 'し', romaji: 'shi', kategori: 'sa-gyou' },
    { char: 'す', romaji: 'su', kategori: 'sa-gyou' },
    { char: 'せ', romaji: 'se', kategori: 'sa-gyou' },
    { char: 'そ', romaji: 'so', kategori: 'sa-gyou' },
    // Baris TA
    { char: 'た', romaji: 'ta', kategori: 'ta-gyou' },
    { char: 'ち', romaji: 'chi', kategori: 'ta-gyou' },
    { char: 'つ', romaji: 'tsu', kategori: 'ta-gyou' },
    { char: 'て', romaji: 'te', kategori: 'ta-gyou' },
    { char: 'と', romaji: 'to', kategori: 'ta-gyou' },
    // Baris NA
    { char: 'な', romaji: 'na', kategori: 'na-gyou' },
    { char: 'に', romaji: 'ni', kategori: 'na-gyou' },
    { char: 'ぬ', romaji: 'nu', kategori: 'na-gyou' },
    { char: 'ね', romaji: 'ne', kategori: 'na-gyou' },
    { char: 'の', romaji: 'no', kategori: 'na-gyou' },
    // Baris HA
    { char: 'は', romaji: 'ha', kategori: 'ha-gyou' },
    { char: 'ひ', romaji: 'hi', kategori: 'ha-gyou' },
    { char: 'ふ', romaji: 'fu', kategori: 'ha-gyou' },
    { char: 'へ', romaji: 'he', kategori: 'ha-gyou' },
    { char: 'ほ', romaji: 'ho', kategori: 'ha-gyou' },
    // Baris MA
    { char: 'ま', romaji: 'ma', kategori: 'ma-gyou' },
    { char: 'み', romaji: 'mi', kategori: 'ma-gyou' },
    { char: 'む', romaji: 'mu', kategori: 'ma-gyou' },
    { char: 'め', romaji: 'me', kategori: 'ma-gyou' },
    { char: 'も', romaji: 'mo', kategori: 'ma-gyou' },
    // Baris YA
    { char: 'や', romaji: 'ya', kategori: 'ya-gyou' },
    { char: 'ゆ', romaji: 'yu', kategori: 'ya-gyou' },
    { char: 'よ', romaji: 'yo', kategori: 'ya-gyou' },
    // Baris RA
    { char: 'ら', romaji: 'ra', kategori: 'ra-gyou' },
    { char: 'り', romaji: 'ri', kategori: 'ra-gyou' },
    { char: 'る', romaji: 'ru', kategori: 'ra-gyou' },
    { char: 'れ', romaji: 're', kategori: 'ra-gyou' },
    { char: 'ろ', romaji: 'ro', kategori: 'ra-gyou' },
    // WA & N
    { char: 'わ', romaji: 'wa', kategori: 'wa-gyou' },
    { char: 'を', romaji: 'wo', kategori: 'wa-gyou' },
    { char: 'ん', romaji: 'n', kategori: 'wa-gyou' }
];

// KATAKANA (46 karakter dasar)
const katakanaData = [
    // Baris A
    { char: 'ア', romaji: 'a', kategori: 'a-gyou' },
    { char: 'イ', romaji: 'i', kategori: 'a-gyou' },
    { char: 'ウ', romaji: 'u', kategori: 'a-gyou' },
    { char: 'エ', romaji: 'e', kategori: 'a-gyou' },
    { char: 'オ', romaji: 'o', kategori: 'a-gyou' },
    // Baris KA
    { char: 'カ', romaji: 'ka', kategori: 'ka-gyou' },
    { char: 'キ', romaji: 'ki', kategori: 'ka-gyou' },
    { char: 'ク', romaji: 'ku', kategori: 'ka-gyou' },
    { char: 'ケ', romaji: 'ke', kategori: 'ka-gyou' },
    { char: 'コ', romaji: 'ko', kategori: 'ka-gyou' },
    // Baris SA
    { char: 'サ', romaji: 'sa', kategori: 'sa-gyou' },
    { char: 'シ', romaji: 'shi', kategori: 'sa-gyou' },
    { char: 'ス', romaji: 'su', kategori: 'sa-gyou' },
    { char: 'セ', romaji: 'se', kategori: 'sa-gyou' },
    { char: 'ソ', romaji: 'so', kategori: 'sa-gyou' },
    // Baris TA
    { char: 'タ', romaji: 'ta', kategori: 'ta-gyou' },
    { char: 'チ', romaji: 'chi', kategori: 'ta-gyou' },
    { char: 'ツ', romaji: 'tsu', kategori: 'ta-gyou' },
    { char: 'テ', romaji: 'te', kategori: 'ta-gyou' },
    { char: 'ト', romaji: 'to', kategori: 'ta-gyou' },
    // Baris NA
    { char: 'ナ', romaji: 'na', kategori: 'na-gyou' },
    { char: 'ニ', romaji: 'ni', kategori: 'na-gyou' },
    { char: 'ヌ', romaji: 'nu', kategori: 'na-gyou' },
    { char: 'ネ', romaji: 'ne', kategori: 'na-gyou' },
    { char: 'ノ', romaji: 'no', kategori: 'na-gyou' },
    // Baris HA
    { char: 'ハ', romaji: 'ha', kategori: 'ha-gyou' },
    { char: 'ヒ', romaji: 'hi', kategori: 'ha-gyou' },
    { char: 'フ', romaji: 'fu', kategori: 'ha-gyou' },
    { char: 'ヘ', romaji: 'he', kategori: 'ha-gyou' },
    { char: 'ホ', romaji: 'ho', kategori: 'ha-gyou' },
    // Baris MA
    { char: 'マ', romaji: 'ma', kategori: 'ma-gyou' },
    { char: 'ミ', romaji: 'mi', kategori: 'ma-gyou' },
    { char: 'ム', romaji: 'mu', kategori: 'ma-gyou' },
    { char: 'メ', romaji: 'me', kategori: 'ma-gyou' },
    { char: 'モ', romaji: 'mo', kategori: 'ma-gyou' },
    // Baris YA
    { char: 'ヤ', romaji: 'ya', kategori: 'ya-gyou' },
    { char: 'ユ', romaji: 'yu', kategori: 'ya-gyou' },
    { char: 'ヨ', romaji: 'yo', kategori: 'ya-gyou' },
    // Baris RA
    { char: 'ラ', romaji: 'ra', kategori: 'ra-gyou' },
    { char: 'リ', romaji: 'ri', kategori: 'ra-gyou' },
    { char: 'ル', romaji: 'ru', kategori: 'ra-gyou' },
    { char: 'レ', romaji: 're', kategori: 'ra-gyou' },
    { char: 'ロ', romaji: 'ro', kategori: 'ra-gyou' },
    // WA & N
    { char: 'ワ', romaji: 'wa', kategori: 'wa-gyou' },
    { char: 'ヲ', romaji: 'wo', kategori: 'wa-gyou' },
    { char: 'ン', romaji: 'n', kategori: 'wa-gyou' }
];

// KANJI N5 (103 karakter - JLPT N5)
const kanjiN5Data = [
    { char: '一', onyomi: 'イチ、イツ', kunyomi: 'ひと、ひと.つ', arti: 'satu', level: 'N5', contoh: '一人 (hitori) = seorang' },
    { char: '二', onyomi: 'ニ', kunyomi: 'ふた、ふた.つ', arti: 'dua', level: 'N5', contoh: '二人 (futari) = dua orang' },
    { char: '三', onyomi: 'サン', kunyomi: 'み、み.つ', arti: 'tiga', level: 'N5', contoh: '三日 (mikka) = tiga hari' },
    { char: '四', onyomi: 'シ', kunyomi: 'よ、よ.つ、よん', arti: 'empat', level: 'N5', contoh: '四月 (shigatsu) = April' },
    { char: '五', onyomi: 'ゴ', kunyomi: 'いつ、いつ.つ', arti: 'lima', level: 'N5', contoh: '五日 (itsuka) = lima hari' },
    { char: '六', onyomi: 'ロク', kunyomi: 'む、む.つ', arti: 'enam', level: 'N5', contoh: '六月 (rokugatsu) = Juni' },
    { char: '七', onyomi: 'シチ', kunyomi: 'なな、なな.つ', arti: 'tujuh', level: 'N5', contoh: '七日 (nanoka) = tujuh hari' },
    { char: '八', onyomi: 'ハチ', kunyomi: 'や、や.つ', arti: 'delapan', level: 'N5', contoh: '八月 (hachigatsu) = Agustus' },
    { char: '九', onyomi: 'キュウ、ク', kunyomi: 'ここの、ここの.つ', arti: 'sembilan', level: 'N5', contoh: '九時 (kuji) = jam 9' },
    { char: '十', onyomi: 'ジュウ、ジッ', kunyomi: 'とお、と', arti: 'sepuluh', level: 'N5', contoh: '十日 (tooka) = tanggal 10' },
    { char: '百', onyomi: 'ヒャク', kunyomi: '', arti: 'seratus', level: 'N5', contoh: '百円 (hyaku en) = 100 yen' },
    { char: '千', onyomi: 'セン', kunyomi: 'ち', arti: 'seribu', level: 'N5', contoh: '千円 (sen en) = 1000 yen' },
    { char: '万', onyomi: 'マン、バン', kunyomi: '', arti: 'sepuluh ribu', level: 'N5', contoh: '一万 (ichiman) = 10.000' },
    { char: '円', onyomi: 'エン', kunyomi: 'まる', arti: 'yen, lingkaran', level: 'N5', contoh: '五百円 (gohyaku en) = 500 yen' },
    { char: '日', onyomi: 'ニチ、ジツ', kunyomi: 'ひ、か', arti: 'hari, matahari', level: 'N5', contoh: '今日 (kyou) = hari ini' },
    { char: '月', onyomi: 'ゲツ、ガツ', kunyomi: 'つき', arti: 'bulan', level: 'N5', contoh: '一月 (ichigatsu) = Januari' },
    { char: '火', onyomi: 'カ', kunyomi: 'ひ', arti: 'api', level: 'N5', contoh: '火曜日 (kayoubi) = Selasa' },
    { char: '水', onyomi: 'スイ', kunyomi: 'みず', arti: 'air', level: 'N5', contoh: '水曜日 (suiyoubi) = Rabu' },
    { char: '木', onyomi: 'モク、ボク', kunyomi: 'き、こ', arti: 'kayu, pohon', level: 'N5', contoh: '木曜日 (mokuyoubi) = Kamis' },
    { char: '金', onyomi: 'キン、コン', kunyomi: 'かね、かな', arti: 'emas, uang', level: 'N5', contoh: '金曜日 (kinyoubi) = Jumat' },
    { char: '土', onyomi: 'ド、ト', kunyomi: 'つち', arti: 'tanah', level: 'N5', contoh: '土曜日 (doyoubi) = Sabtu' },
    { char: '人', onyomi: 'ジン、ニン', kunyomi: 'ひと', arti: 'orang', level: 'N5', contoh: '日本人 (nihonjin) = orang Jepang' },
    { char: '本', onyomi: 'ホン', kunyomi: 'もと', arti: 'buku, asal', level: 'N5', contoh: '日本 (nihon) = Jepang' },
    { char: '国', onyomi: 'コク', kunyomi: 'くに', arti: 'negara', level: 'N5', contoh: '外国 (gaikoku) = luar negeri' },
    { char: '山', onyomi: 'サン', kunyomi: 'やま', arti: 'gunung', level: 'N5', contoh: '富士山 (fujisan) = Gunung Fuji' },
    { char: '川', onyomi: 'セン', kunyomi: 'かわ', arti: 'sungai', level: 'N5', contoh: '川 (kawa) = sungai' },
    { char: '田', onyomi: 'デン', kunyomi: 'た', arti: 'sawah', level: 'N5', contoh: '田中 (tanaka) = nama keluarga' },
    { char: '学', onyomi: 'ガク', kunyomi: 'まな.ぶ', arti: 'belajar', level: 'N5', contoh: '学生 (gakusei) = siswa' },
    { char: '生', onyomi: 'セイ、ショウ', kunyomi: 'い.きる、う.まれる', arti: 'hidup, lahir', level: 'N5', contoh: '先生 (sensei) = guru' },
    { char: '先', onyomi: 'セン', kunyomi: 'さき', arti: 'sebelum, depan', level: 'N5', contoh: '先週 (senshuu) = minggu lalu' },
    { char: '年', onyomi: 'ネン', kunyomi: 'とし', arti: 'tahun', level: 'N5', contoh: '今年 (kotoshi) = tahun ini' },
    { char: '校', onyomi: 'コウ', kunyomi: '', arti: 'sekolah', level: 'N5', contoh: '学校 (gakkou) = sekolah' },
    { char: '語', onyomi: 'ゴ', kunyomi: 'かた.る', arti: 'bahasa', level: 'N5', contoh: '日本語 (nihongo) = bahasa Jepang' },
    { char: '文', onyomi: 'ブン、モン', kunyomi: 'ふみ', arti: 'teks, tulisan', level: 'N5', contoh: '文 (bun) = kalimat' },
    { char: '字', onyomi: 'ジ', kunyomi: 'あざ', arti: 'huruf', level: 'N5', contoh: '漢字 (kanji) = huruf kanji' },
    { char: '大', onyomi: 'ダイ、タイ', kunyomi: 'おお.きい', arti: 'besar', level: 'N5', contoh: '大学 (daigaku) = universitas' },
    { char: '小', onyomi: 'ショウ', kunyomi: 'ちい.さい、こ', arti: 'kecil', level: 'N5', contoh: '小学校 (shougakkou) = SD' },
    { char: '中', onyomi: 'チュウ', kunyomi: 'なか', arti: 'tengah, di dalam', level: 'N5', contoh: '中学校 (chuugakkou) = SMP' },
    { char: '高', onyomi: 'コウ', kunyomi: 'たか.い', arti: 'tinggi, mahal', level: 'N5', contoh: '高校 (koukou) = SMA' },
    { char: '上', onyomi: 'ジョウ', kunyomi: 'うえ、あ.がる', arti: 'atas', level: 'N5', contoh: '上手 (jouzu) = pintar' },
    { char: '下', onyomi: 'カ、ゲ', kunyomi: 'した、さ.がる', arti: 'bawah', level: 'N5', contoh: '下手 (heta) = tidak mahir' },
    { char: '左', onyomi: 'サ', kunyomi: 'ひだり', arti: 'kiri', level: 'N5', contoh: '左 (hidari) = kiri' },
    { char: '右', onyomi: 'ウ、ユウ', kunyomi: 'みぎ', arti: 'kanan', level: 'N5', contoh: '右 (migi) = kanan' },
    { char: '前', onyomi: 'ゼン', kunyomi: 'まえ', arti: 'depan, sebelum', level: 'N5', contoh: '午前 (gozen) = pagi' },
    { char: '後', onyomi: 'ゴ、コウ', kunyomi: 'のち、うし.ろ', arti: 'belakang, setelah', level: 'N5', contoh: '午後 (gogo) = siang/sore' },
    { char: '内', onyomi: 'ナイ', kunyomi: 'うち', arti: 'dalam', level: 'N5', contoh: '家内 (kanai) = istri' },
    { char: '外', onyomi: 'ガイ、ゲ', kunyomi: 'そと、ほか', arti: 'luar', level: 'N5', contoh: '外国 (gaikoku) = luar negeri' },
    { char: '南', onyomi: 'ナン', kunyomi: 'みなみ', arti: 'selatan', level: 'N5', contoh: '南 (minami) = selatan' },
    { char: '北', onyomi: 'ホク', kunyomi: 'きた', arti: 'utara', level: 'N5', contoh: '北 (kita) = utara' },
    { char: '東', onyomi: 'トウ', kunyomi: 'ひがし', arti: 'timur', level: 'N5', contoh: '東京 (toukyou) = Tokyo' },
    { char: '西', onyomi: 'セイ、サイ', kunyomi: 'にし', arti: 'barat', level: 'N5', contoh: '西 (nishi) = barat' },
    { char: '今', onyomi: 'コン、キン', kunyomi: 'いま', arti: 'sekarang', level: 'N5', contoh: '今日 (kyou) = hari ini' },
    { char: '時', onyomi: 'ジ', kunyomi: 'とき', arti: 'waktu, jam', level: 'N5', contoh: '時間 (jikan) = waktu' },
    { char: '間', onyomi: 'カン、ケン', kunyomi: 'あいだ、ま', arti: 'interval, antara', level: 'N5', contoh: '時間 (jikan) = waktu' },
    { char: '分', onyomi: 'ブン、フン', kunyomi: 'わ.ける', arti: 'menit, membagi', level: 'N5', contoh: '十分 (juppun) = 10 menit' },
    { char: '半', onyomi: 'ハン', kunyomi: 'なか.ば', arti: 'setengah', level: 'N5', contoh: '半分 (hanbun) = setengah' },
    { char: '毎', onyomi: 'マイ', kunyomi: '', arti: 'setiap', level: 'N5', contoh: '毎日 (mainichi) = setiap hari' },
    { char: '何', onyomi: 'カ', kunyomi: 'なに、なん', arti: 'apa', level: 'N5', contoh: '何 (nani) = apa' },
    { char: '名', onyomi: 'メイ、ミョウ', kunyomi: 'な', arti: 'nama', level: 'N5', contoh: '名前 (namae) = nama' },
    { char: '目', onyomi: 'モク', kunyomi: 'め', arti: 'mata', level: 'N5', contoh: '目 (me) = mata' },
    { char: '耳', onyomi: 'ジ', kunyomi: 'みみ', arti: 'telinga', level: 'N5', contoh: '耳 (mimi) = telinga' },
    { char: '口', onyomi: 'コウ、ク', kunyomi: 'くち', arti: 'mulut', level: 'N5', contoh: '口 (kuchi) = mulut' },
    { char: '手', onyomi: 'シュ', kunyomi: 'て', arti: 'tangan', level: 'N5', contoh: '手紙 (tegami) = surat' },
    { char: '足', onyomi: 'ソク', kunyomi: 'あし、た.りる', arti: 'kaki', level: 'N5', contoh: '足 (ashi) = kaki' },
    { char: '見', onyomi: 'ケン', kunyomi: 'み.る', arti: 'melihat', level: 'N5', contoh: '見る (miru) = melihat' },
    { char: '聞', onyomi: 'ブン、モン', kunyomi: 'き.く', arti: 'mendengar', level: 'N5', contoh: '聞く (kiku) = mendengar' },
    { char: '食', onyomi: 'ショク', kunyomi: 'た.べる', arti: 'makan', level: 'N5', contoh: '食べる (taberu) = makan' },
    { char: '飲', onyomi: 'イン', kunyomi: 'の.む', arti: 'minum', level: 'N5', contoh: '飲む (nomu) = minum' },
    { char: '買', onyomi: 'バイ', kunyomi: 'か.う', arti: 'membeli', level: 'N5', contoh: '買う (kau) = membeli' },
    { char: '売', onyomi: 'バイ', kunyomi: 'う.る', arti: 'menjual', level: 'N5', contoh: '売る (uru) = menjual' },
    { char: '読', onyomi: 'ドク、トク', kunyomi: 'よ.む', arti: 'membaca', level: 'N5', contoh: '読む (yomu) = membaca' },
    { char: '書', onyomi: 'ショ', kunyomi: 'か.く', arti: 'menulis', level: 'N5', contoh: '書く (kaku) = menulis' },
    { char: '話', onyomi: 'ワ', kunyomi: 'はな.す', arti: 'berbicara', level: 'N5', contoh: '話す (hanasu) = berbicara' },
    { char: '言', onyomi: 'ゲン、ゴン', kunyomi: 'い.う、こと', arti: 'berkata', level: 'N5', contoh: '言う (iu) = berkata' },
    { char: '行', onyomi: 'コウ、ギョウ', kunyomi: 'い.く、ゆ.く', arti: 'pergi', level: 'N5', contoh: '行く (iku) = pergi' },
    { char: '来', onyomi: 'ライ', kunyomi: 'く.る', arti: 'datang', level: 'N5', contoh: '来る (kuru) = datang' },
    { char: '帰', onyomi: 'キ', kunyomi: 'かえ.る', arti: 'pulang', level: 'N5', contoh: '帰る (kaeru) = pulang' },
    { char: '出', onyomi: 'シュツ', kunyomi: 'で.る', arti: 'keluar', level: 'N5', contoh: '出る (deru) = keluar' },
    { char: '入', onyomi: 'ニュウ', kunyomi: 'はい.る、い.れる', arti: 'masuk', level: 'N5', contoh: '入る (hairu) = masuk' },
    { char: '立', onyomi: 'リツ', kunyomi: 'た.つ', arti: 'berdiri', level: 'N5', contoh: '立つ (tatsu) = berdiri' },
    { char: '休', onyomi: 'キュウ', kunyomi: 'やす.む', arti: 'istirahat', level: 'N5', contoh: '休む (yasumu) = istirahat' },
    { char: '作', onyomi: 'サク、サ', kunyomi: 'つく.る', arti: 'membuat', level: 'N5', contoh: '作る (tsukuru) = membuat' },
    { char: '持', onyomi: 'ジ', kunyomi: 'も.つ', arti: 'memegang', level: 'N5', contoh: '持つ (motsu) = memegang' },
    { char: '待', onyomi: 'タイ', kunyomi: 'ま.つ', arti: 'menunggu', level: 'N5', contoh: '待つ (matsu) = menunggu' },
    { char: '住', onyomi: 'ジュウ', kunyomi: 'す.む', arti: 'tinggal', level: 'N5', contoh: '住む (sumu) = tinggal' },
    { char: '教', onyomi: 'キョウ', kunyomi: 'おし.える', arti: 'mengajar', level: 'N5', contoh: '教える (oshieru) = mengajar' },
    { char: '会', onyomi: 'カイ、エ', kunyomi: 'あ.う', arti: 'bertemu', level: 'N5', contoh: '会う (au) = bertemu' },
    { char: '社', onyomi: 'シャ', kunyomi: 'やしろ', arti: 'perusahaan', level: 'N5', contoh: '会社 (kaisha) = perusahaan' },
    { char: '駅', onyomi: 'エキ', kunyomi: '', arti: 'stasiun', level: 'N5', contoh: '駅 (eki) = stasiun' },
    { char: '店', onyomi: 'テン', kunyomi: 'みせ', arti: 'toko', level: 'N5', contoh: '店 (mise) = toko' },
    { char: '車', onyomi: 'シャ', kunyomi: 'くるま', arti: 'mobil, kendaraan', level: 'N5', contoh: '車 (kuruma) = mobil' },
    { char: '電', onyomi: 'デン', kunyomi: '', arti: 'listrik', level: 'N5', contoh: '電車 (densha) = kereta' },
    { char: '雨', onyomi: 'ウ', kunyomi: 'あめ', arti: 'hujan', level: 'N5', contoh: '雨 (ame) = hujan' },
    { char: '天', onyomi: 'テン', kunyomi: 'あま、あめ', arti: 'langit, surga', level: 'N5', contoh: '天気 (tenki) = cuaca' },
    { char: '気', onyomi: 'キ、ケ', kunyomi: '', arti: 'energi, perasaan', level: 'N5', contoh: '元気 (genki) = sehat' },
    { char: '花', onyomi: 'カ', kunyomi: 'はな', arti: 'bunga', level: 'N5', contoh: '花 (hana) = bunga' },
    { char: '物', onyomi: 'ブツ、モツ', kunyomi: 'もの', arti: 'benda', level: 'N5', contoh: '食べ物 (tabemono) = makanan' },
    { char: '犬', onyomi: 'ケン', kunyomi: 'いぬ', arti: 'anjing', level: 'N5', contoh: '犬 (inu) = anjing' },
    { char: '猫', onyomi: 'ビョウ', kunyomi: 'ねこ', arti: 'kucing', level: 'N5', contoh: '猫 (neko) = kucing' },
    { char: '鳥', onyomi: 'チョウ', kunyomi: 'とり', arti: 'burung', level: 'N5', contoh: '鳥 (tori) = burung' },
    { char: '魚', onyomi: 'ギョ', kunyomi: 'うお、さかな', arti: 'ikan', level: 'N5', contoh: '魚 (sakana) = ikan' },
    { char: '肉', onyomi: 'ニク', kunyomi: '', arti: 'daging', level: 'N5', contoh: '肉 (niku) = daging' },
    { char: '友', onyomi: 'ユウ', kunyomi: 'とも', arti: 'teman', level: 'N5', contoh: '友達 (tomodachi) = teman' },
    { char: '父', onyomi: 'フ', kunyomi: 'ちち', arti: 'ayah', level: 'N5', contoh: '父 (chichi) = ayah' },
    { char: '母', onyomi: 'ボ', kunyomi: 'はは', arti: 'ibu', level: 'N5', contoh: '母 (haha) = ibu' },
    { char: '兄', onyomi: 'ケイ、キョウ', kunyomi: 'あに', arti: 'kakak laki-laki', level: 'N5', contoh: '兄 (ani) = kakak laki' }
];

// KANJI N4 (168 karakter tambahan - menambah dari N5)
const kanjiN4Data = [
    { char: '便', onyomi: 'ベン、ビン', kunyomi: 'たよ.り', arti: 'kemudahan, surat', level: 'N4', contoh: '便利 (benri) = praktis' },
    { char: '利', onyomi: 'リ', kunyomi: 'き.く', arti: 'keuntungan', level: 'N4', contoh: '便利 (benri) = praktis' },
    { char: '別', onyomi: 'ベツ', kunyomi: 'わか.れる', arti: 'terpisah, berbeda', level: 'N4', contoh: '別々 (betsubetsu) = terpisah' },
    { char: '世', onyomi: 'セイ、セ', kunyomi: 'よ', arti: 'dunia, generasi', level: 'N4', contoh: '世界 (sekai) = dunia' },
    { char: '界', onyomi: 'カイ', kunyomi: '', arti: 'dunia, batas', level: 'N4', contoh: '世界 (sekai) = dunia' },
    { char: '主', onyomi: 'シュ、ス', kunyomi: 'ぬし、おも', arti: 'utama, tuan', level: 'N4', contoh: '主人 (shujin) = suami' },
    { char: '仕', onyomi: 'シ、ジ', kunyomi: 'つか.える', arti: 'melayani, pekerjaan', level: 'N4', contoh: '仕事 (shigoto) = pekerjaan' },
    { char: '事', onyomi: 'ジ、ズ', kunyomi: 'こと', arti: 'hal, urusan', level: 'N4', contoh: '仕事 (shigoto) = pekerjaan' },
    { char: '以', onyomi: 'イ', kunyomi: 'もっ.て', arti: 'dengan, dari', level: 'N4', contoh: '以上 (ijou) = lebih dari' },
    { char: '体', onyomi: 'タイ、テイ', kunyomi: 'からだ', arti: 'tubuh', level: 'N4', contoh: '体 (karada) = tubuh' },
    { char: '使', onyomi: 'シ', kunyomi: 'つか.う', arti: 'menggunakan', level: 'N4', contoh: '使う (tsukau) = menggunakan' },
    { char: '借', onyomi: 'シャク', kunyomi: 'か.りる', arti: 'meminjam', level: 'N4', contoh: '借りる (kariru) = meminjam' },
    { char: '供', onyomi: 'キョウ', kunyomi: 'とも、そな.える', arti: 'menyediakan', level: 'N4', contoh: '子供 (kodomo) = anak' },
    { char: '係', onyomi: 'ケイ', kunyomi: 'かか.る', arti: 'berhubungan', level: 'N4', contoh: '関係 (kankei) = hubungan' },
    { char: '信', onyomi: 'シン', kunyomi: 'しん.じる', arti: 'percaya', level: 'N4', contoh: '信じる (shinjiru) = percaya' },
    { char: '倍', onyomi: 'バイ', kunyomi: '', arti: 'lipat', level: 'N4', contoh: '二倍 (nibai) = dua kali lipat' },
    { char: '全', onyomi: 'ゼン', kunyomi: 'まった.く', arti: 'semua, seluruhnya', level: 'N4', contoh: '全部 (zenbu) = semuanya' },
    { char: '具', onyomi: 'グ', kunyomi: '', arti: 'alat', level: 'N4', contoh: '道具 (dougu) = alat' },
    { char: '典', onyomi: 'テン', kunyomi: '', arti: 'kode, buku', level: 'N4', contoh: '辞典 (jiten) = kamus' },
    { char: '冷', onyomi: 'レイ', kunyomi: 'つめ.たい、ひ.える', arti: 'dingin', level: 'N4', contoh: '冷たい (tsumetai) = dingin' },
    { char: '初', onyomi: 'ショ', kunyomi: 'はじ.め', arti: 'pertama kali', level: 'N4', contoh: '初めて (hajimete) = pertama kali' },
    { char: '切', onyomi: 'セツ、サイ', kunyomi: 'き.る', arti: 'memotong', level: 'N4', contoh: '切る (kiru) = memotong' },
    { char: '列', onyomi: 'レツ', kunyomi: '', arti: 'baris, barisan', level: 'N4', contoh: '列 (retsu) = barisan' },
    { char: '動', onyomi: 'ドウ', kunyomi: 'うご.く', arti: 'bergerak', level: 'N4', contoh: '動く (ugoku) = bergerak' },
    { char: '務', onyomi: 'ム', kunyomi: 'つと.める', arti: 'tugas', level: 'N4', contoh: '勉強 (benkyou) = belajar' },
    { char: '勝', onyomi: 'ショウ', kunyomi: 'か.つ', arti: 'menang', level: 'N4', contoh: '勝つ (katsu) = menang' },
    { char: '化', onyomi: 'カ、ケ', kunyomi: 'ば.ける', arti: 'perubahan', level: 'N4', contoh: '文化 (bunka) = budaya' },
    { char: '医', onyomi: 'イ', kunyomi: '', arti: 'medis, dokter', level: 'N4', contoh: '医者 (isha) = dokter' },
    { char: '去', onyomi: 'キョ、コ', kunyomi: 'さ.る', arti: 'pergi, masa lalu', level: 'N4', contoh: '過去 (kako) = masa lalu' },
    { char: '反', onyomi: 'ハン、ホン', kunyomi: 'そ.る', arti: 'berlawanan', level: 'N4', contoh: '反対 (hantai) = berlawanan' },
    { char: '取', onyomi: 'シュ', kunyomi: 'と.る', arti: 'mengambil', level: 'N4', contoh: '取る (toru) = mengambil' },
    { char: '受', onyomi: 'ジュ', kunyomi: 'う.ける', arti: 'menerima', level: 'N4', contoh: '受ける (ukeru) = menerima' },
    { char: '味', onyomi: 'ミ', kunyomi: 'あじ、あじ.わう', arti: 'rasa', level: 'N4', contoh: '味 (aji) = rasa' },
    { char: '品', onyomi: 'ヒン', kunyomi: 'しな', arti: 'barang, produk', level: 'N4', contoh: '品物 (shinamono) = barang' },
    { char: '員', onyomi: 'イン', kunyomi: '', arti: 'anggota', level: 'N4', contoh: '会社員 (kaishain) = pegawai' },
    { char: '問', onyomi: 'モン', kunyomi: 'と.う', arti: 'pertanyaan', level: 'N4', contoh: '質問 (shitsumon) = pertanyaan' },
    { char: '場', onyomi: 'ジョウ', kunyomi: 'ば', arti: 'tempat', level: 'N4', contoh: '場所 (basho) = tempat' },
    { char: '地', onyomi: 'チ、ジ', kunyomi: '', arti: 'tanah, daerah', level: 'N4', contoh: '地図 (chizu) = peta' },
    { char: '堂', onyomi: 'ドウ', kunyomi: '', arti: 'aula, bangunan', level: 'N4', contoh: '食堂 (shokudou) = kantin' },
    { char: '変', onyomi: 'ヘン', kunyomi: 'か.わる', arti: 'berubah, aneh', level: 'N4', contoh: '変わる (kawaru) = berubah' },
    { char: '夏', onyomi: 'カ、ゲ', kunyomi: 'なつ', arti: 'musim panas', level: 'N4', contoh: '夏 (natsu) = musim panas' },
    { char: '夕', onyomi: 'セキ', kunyomi: 'ゆう', arti: 'sore', level: 'N4', contoh: '夕方 (yuugata) = sore hari' },
    { char: '夜', onyomi: 'ヤ', kunyomi: 'よる、よ', arti: 'malam', level: 'N4', contoh: '夜 (yoru) = malam' },
    { char: '太', onyomi: 'タイ、タ', kunyomi: 'ふと.い', arti: 'gemuk, tebal', level: 'N4', contoh: '太い (futoi) = tebal' },
    { char: '好', onyomi: 'コウ', kunyomi: 'す.く、この.む', arti: 'suka', level: 'N4', contoh: '好き (suki) = suka' },
    { char: '妹', onyomi: 'マイ', kunyomi: 'いもうと', arti: 'adik perempuan', level: 'N4', contoh: '妹 (imouto) = adik perempuan' },
    { char: '姉', onyomi: 'シ', kunyomi: 'あね', arti: 'kakak perempuan', level: 'N4', contoh: '姉 (ane) = kakak perempuan' },
    { char: '始', onyomi: 'シ', kunyomi: 'はじ.める', arti: 'memulai', level: 'N4', contoh: '始める (hajimeru) = memulai' },
    { char: '字', onyomi: 'ジ', kunyomi: 'あざ', arti: 'huruf, karakter', level: 'N4', contoh: '文字 (moji) = huruf' },
    { char: '安', onyomi: 'アン', kunyomi: 'やす.い', arti: 'murah, aman', level: 'N4', contoh: '安い (yasui) = murah' }
];
